### ISSUE TITLE
FAC Charts

### ISSUE THREAD

**Issue by gregerhardt** [jawadmhoque/transit_ridership_decline#1]
Update FAC Charts as follows: 
 - Separate bus vs rail
 - One line for actual ridership (UPT_ADJ)
 - One line for what the actual ridership would be if the variable stayed at 2002 levels:  UPT_ADJ - XX_FAC_CUM

Charts should look like: 

![image](https://user-images.githubusercontent.com/5774986/69351246-fb35b100-0c48-11ea-9c3e-74f4f4266a4c.png)

Or like: 

![BVA_BART_Emp2](https://user-images.githubusercontent.com/5774986/69351298-143e6200-0c49-11ea-805e-10a17df495eb.png)

**Comment by vsgo222** [comment]
Hi all, 
This task has been completed. 
the code for the task could be found on `..\transit_ridership_decline\Factors and Ridership Data\code` and the script is named > FAC_Charts_Rail_Cumulative
The output could be found in `..\Factors and Ridership Data\Script Outputs` under folders name UPT_ADJ_XX_XXX_CLUSTERS where XX_XXX is the name of the cluster type based on which the charts  are prepared/sorted. 
e.g.  ![Fig 1-10 0 - BUS](https://user-images.githubusercontent.com/56562366/69835456-d8d70100-120f-11ea-9658-27442e5f8a07.png)
