### ISSUE TITLE
FAC Tables for Est6

### ISSUE THREAD

**Issue by gregerhardt** [jawadmhoque/transit_ridership_decline#11]
Update the spreadsheet FAC SAMPLE CALCULATION.xlsx (currently found in Est4) using the data/models in Est6.  Apply for 2012 to 2018 for three APTA clusters plus NY.  

Can we get this by Friday morning, so we can look over this ourselves before the call with GT?

**Comment by jawadmhoque** [comment]
Updated FAC tables. Use the FAC SAMPLE CALCULATION.xlsx
