### ISSUE TITLE
FAC Chart Clean-up

### ISSUE THREAD

**Issue by gregerhardt** [jawadmhoque/transit_ridership_decline#12]
The FAC charts are great.  They should be updated as described below.  Start with the data changes, and then we can do the stylistic stuff after.  

Data changes: 
1. One set of charts for 2002 to 2018, and a separate set for 2012 to 2018.  
2. Add an unexplained trend, calculated from the difference in the modeled vs observed.  
3. Add a chart for gain due to "New Reporters".  This is based on the ridership in the first year a metro area/mode shows up in the data, as we looked at the other day.  

Stylistic changes: 
1. TNCs, Bike Share and Scooters are all segmented by bus vs rail, taking up 6 spots.  However, each set of charts is specific to bus vs rail, so 3 of them are unnecessary.  Use just the appropriate set to save space.  Probably the simplest thing to do is sum the bus and rail columns for these three factors (one will always be zero) and plot that. 
2. Switch the red and green colors. 
3. Drop duplicate lines on NYC rail. 
4. Drop duplicate legends as needed. 
5. Use meaningful cluster descriptions. 
6. Use meaningful variable descriptions (i.e. Vehicle Revenue Miles, Fare, Population + Employment, Income, Gas Price, Immigrant Population, 0 Vehicle Household Share, Transit Supportive Density Share, Work at Home Share, Rail Competition, TNCs, Bike Share, Scooters)
7. Consider whether #6 should be in the legend, or as a title for each sub-figure.  
8. Fix years on right-most column of charts.

**Comment by gregerhardt** [comment]
I am working on #2 right now.  Will add #3 next if I get a chance.

**Comment by vsgo222** [comment]
The following task are completed. 
Data changes:  

1. One set of charts for 2002 to 2018, and a separate set for 2012 to 2018.

Stylistic changes:

1. Switch the red and green colors.
2. Drop duplicate legends as needed.
3. Use meaningful cluster descriptions.
4. Use meaningful variable descriptions (i.e. Vehicle Revenue Miles, Fare, Population + Employment, Income, Gas Price, Immigrant Population, 0 Vehicle Household Share, Transit Supportive Density Share, Work at Home Share, Rail Competition, TNCs, Bike Share, Scooters)
5. Fix years on the right-most column of charts.



![Est6 - 2002-2018 Cluster 10 0-RAIL](https://user-images.githubusercontent.com/56562366/70754814-2f5f3780-1d06-11ea-8c7d-17d05c8ee674.png)
![Est6 - 2012-2018 Cluster 10 0-RAIL](https://user-images.githubusercontent.com/56562366/70754815-2f5f3780-1d06-11ea-809f-0046b40560fb.png)

**Comment by vsgo222** [comment]
Remaining task also completed as scheduled and discussed
