### ISSUE TITLE
Make an FAC chart for every metro area

### ISSUE THREAD

**Issue by gregerhardt** [jawadmhoque/transit_ridership_decline#18]
I'd like you to create a set of 2002 base FAC charts for each metro area and mode combination.  I think the file FAC.csv includes all the data you need for this.  This should help us with QA/QC.

**Comment by vsgo222** [comment]
Hello all.
I have created the FAC Charts for all metro areas. 
You can find 
1. The output: ..Factors and Ridership Data\Script Outputs\Est7_Outputs\Metro_Area
2. The code: ..Factors and Ridership Data\code\UPT_FAC_Metro_Area.py

**Comment by gregerhardt** [comment]
Thanks for this.  The charts look good, but flipping through them, I think we are showing the year-over-year change, and not the cumulative change.  We can use New York as a comparison point, as that should be the same in both the clusters and the individual cities.

**Comment by vsgo222** [comment]
> Thanks for this. The charts look good, but flipping through them, I think we are showing the year-over-year change, and not the cumulative change. We can use New York as a comparison point, as that should be the same in both the clusters and the individual cities.

The graphs are now updated and represent it correctly.
