### ISSUE TITLE
Clean up fare data

### ISSUE THREAD

**Issue by gregerhardt** [jawadmhoque/transit_ridership_decline#3]
Look through charts showing average fares.  Identify spikes.  Investigate whether the data can be traced to the NTC, or if it is a bug in our aggregation of those data.  IF the former, create overrides to smooth.

**Comment by jawadmhoque** [comment]
There is an updated csv file on the Estimation_File folder. It contains two new rows: FARE_ADJ and FARE_ADJ_ORIGINAL. I looked at the MSAs individually to identify sudden jumps or drops in the Fare and UPT data. Corrected/  Interpolated/ Averaged where necessary. The NOTE column references such changes. But would be useful to sort the whole dataframe by PROBLEM_FLAG to see where additional assumptions are needed.
