### ISSUE TITLE
Create lag variables

### ISSUE THREAD

**Issue by gregerhardt** [jawadmhoque/transit_ridership_decline#4]
Create lag variables for: VRM, FARE, Scooters, Bikes, TNCs.  Defined as:

lag (shift) 1-3 years
distributed lag (scales up) 1-3 years (5 years for TNC)
for VRM and FARE, separate positive and negative.

**Comment by jawadmhoque** [comment]
Confused on the Distributed Lags.

**Comment by gregerhardt** [comment]
We are ok here.  Tested.
